### ISSUE TITLE
 TM Processing L0: 21.6.21 Pixel Mask NIX00442 changed withing request

### ISSUE THREAD

**Issue by nicHoch** [i4Ds/STIXCore#248]
2022-07-10 04:44:53,234 VerifyWarning: Card is too long, comment will be truncated.
2022-07-10 04:45:35,525 NIX00442 has changed in complete packet sequence
2022-07-10 04:45:35,633 Error processing file /data/stix/out/test/bsdfull/LB/21/6/21/solo_LB_stix-21-6-21_0000000000-9999999999_V01_2203306666-49334.fits for 21, 6, 21
Traceback (most recent call last):
  File "/home/nicky/STIXCore/stixcore/processing/LBtoL0.py", line 100, in process_tm_type
    level0 = tmp.from_levelb(comp, parent=file.name)
  File "/home/nicky/STIXCore/stixcore/products/level0/scienceL0.py", line 303, in from_levelb
    data.add_data('pixel_masks', (pixel_masks, pm_meta))
  File "/home/nicky/STIXCore/stixcore/products/product.py", line 96, in add_data
    self[name] = data
  File "/home/nicky/STIXCore/venv/lib/python3.8/site-packages/astropy/table/table.py", line 1904, in __setitem__
    self.add_column(value, name=item, copy=True)
  File "/home/nicky/STIXCore/venv/lib/python3.8/site-packages/astropy/table/table.py", line 2193, in add_column
    raise ValueError('Inconsistent data column lengths')
ValueError: Inconsistent data column lengths
2022-07-10 04:45:35,634 Inconsistent data column lengths
2022-07-10 04:45:57,154 VerifyWarning: Card is too long, comment will be truncated.
2022-07-10 04:46:18,637 VerifyWarning: Card is too long, comment will be truncated.

2022-07-08 18:06:57,187 Error processing file /data/stix/out/test/bsdfull/LB/21/6/21/solo_LB_stix-21-6-21_0000000000-9999999999_V01_2204023791-49337.fits for 21, 6, 21
2022-07-08 22:09:17,316 Error processing file /data/stix/out/test/bsdfull/LB/21/6/21/solo_LB_stix-21-6-21_0000000000-9999999999_V01_2203310588-65252.fits for 21, 6, 21
2022-07-09 01:07:46,602 Error processing file /data/stix/out/test/bsdfull/LB/21/6/21/solo_LB_stix-21-6-21_0000000000-9999999999_V01_2204205483-50208.fits for 21, 6, 21
2022-07-09 03:31:21,808 Error processing file /data/stix/out/test/bsdfull/LB/21/6/21/solo_LB_stix-21-6-21_0000000000-9999999999_V01_2205045360-50393.fits for 21, 6, 21
2022-07-09 03:33:30,157 Error processing file /data/stix/out/test/bsdfull/LB/21/6/21/solo_LB_stix-21-6-21_0000000000-9999999999_V01_2204027774-49303.fits for 21, 6, 21
2022-07-09 07:56:42,920 Error processing file /data/stix/out/test/bsdfull/LB/21/6/21/solo_LB_stix-21-6-21_0000000000-9999999999_V01_2205016629-50355.fits for 21, 6, 21
2022-07-09 10:00:08,900 Error processing file /data/stix/out/test/bsdfull/LB/21/6/21/solo_LB_stix-21-6-21_0000000000-9999999999_V01_2204119148-65206.fits for 21, 6, 21
2022-07-09 17:51:00,898 Error processing file /data/stix/out/test/bsdfull/LB/21/6/21/solo_LB_stix-21-6-21_0000000000-9999999999_V01_2204205232-50225.fits for 21, 6, 21
2022-07-10 01:42:54,161 Error processing file /data/stix/out/test/bsdfull/LB/21/6/21/solo_LB_stix-21-6-21_0000000000-9999999999_V01_2204302915-50354.fits for 21, 6, 21
2022-07-10 04:45:35,633 Error processing file /data/stix/out/test/bsdfull/LB/21/6/21/solo_LB_stix-21-6-21_0000000000-9999999999_V01_2203306666-49334.fits for 21, 6, 21
2022-07-10 07:46:41,069 Error processing file /data/stix/out/test/bsdfull/LB/21/6/21/solo_LB_stix-21-6-21_0000000000-9999999999_V01_2205025913-50213.fits for 21, 6, 21
2022-07-10 10:12:01,853 Error processing file /data/stix/out/test/bsdfull/LB/21/6/21/solo_LB_stix-21-6-21_0000000000-9999999999_V01_2205040105-50218.fits for 21, 6, 21
2022-07-10 11:15:39,354 Error processing file /data/stix/out/test/bsdfull/LB/21/6/21/solo_LB_stix-21-6-21_0000000000-9999999999_V01_2203315831-49317.fits for 21, 6, 21
2022-07-10 11:29:48,811 Error processing file /data/stix/out/test/bsdfull/LB/21/6/21/solo_LB_stix-21-6-21_0000000000-9999999999_V01_2203317187-49240.fits for 21, 6, 21
2022-07-10 15:09:59,352 Error processing file /data/stix/out/test/bsdfull/LB/21/6/21/solo_LB_stix-21-6-21_0000000000-9999999999_V01_2205193651-51931.fits for 21, 6, 21

**Comment by samaloney** [comment]
This isn't a trivial fix as it means the count structure can't just be reshaped as a whole but the differing pixel mask blocks need to be handled separately

**Comment by samaloney** [comment]
So I've fixed this in CPD, SPD and Spectra but I guess the same fix will also be needed in Visibility but as we don't use that at the moment I suggest creating a specific issue for that.

**Comment by samaloney** [comment]
Similar to the RCR bug (#193, i4ds/STIX-FSW#1027) the reported pixel mask will be accurate as shown in the figure below, the vertical line indicates the time the pixel mask change is reported but the counts clearly change after with the pixel mask going from `[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]` to  `[0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0]`
![spec_pixelmask](https://user-images.githubusercontent.com/24570854/183859931-bfaf48df-d733-4dc9-b8e2-59c15addc395.png)
