### ISSUE TITLE
 TM Processing L0: 21,6,21 rebenning counts failed

### ISSUE THREAD

**Issue by nicHoch** [i4Ds/STIXCore#249]
2022-07-09 02:47:48,873 VerifyWarning: Card is too long, comment will be truncated.
2022-07-09 02:47:50,711 Error processing file /data/stix/out/test/bsdfull/LB/21/6/21/solo_LB_stix-21-6-21_0000000000-9999999999_V01_2112090002-51143.fits for 21, 6, 21
Traceback (most recent call last):
  File "/home/nicky/STIXCore/stixcore/processing/LBtoL0.py", line 100, in process_tm_type
    level0 = tmp.from_levelb(comp, parent=file.name)
  File "/home/nicky/STIXCore/stixcore/products/level0/scienceL0.py", line 328, in from_levelb
    counts = counts.reshape(unique_times.size, unique_energies_low.size,
ValueError: cannot reshape array of size 154752 into shape (7,31,32,12)
2022-07-09 02:47:50,712 cannot reshape array of size 154752 into shape (7,31,32,12)
2022-07-09 02:48:05,897 VerifyWarning: Card is too long, comment will be truncated.

**Comment by samaloney** [comment]
This is an odd one the data seems to indicate there should are 7 unique time intervals with 31 energy channels from all 32 detectors and 12 pixels so a total of 83,328 count bins but there are far too many counts bin for this at 154,752. It seem consistent for 13 time bins ...
