### ISSUE TITLE
 TM Processing L0: 21,6,21 Parsing error

### ISSUE THREAD

**Issue by nicHoch** [i4Ds/STIXCore#250]
most likely due to wrong IDB version

see #137 

- [ ]  include the code from #137 to codebase and update IDB lookup 

2022-07-10 02:38:52,731 VerifyWarning: Card is too long, comment will be truncated.
2022-07-10 02:39:00,823 Error processing file /data/stix/out/test/bsdfull/LB/21/6/21/solo_LB_stix-21-6-21_0000000000-9999999999_V01_2203151617-62310.fits for 21, 6, 21
Traceback (most recent call last):
  File "/home/nicky/STIXCore/stixcore/processing/LBtoL0.py", line 100, in process_tm_type
    level0 = tmp.from_levelb(comp, parent=file.name)
  File "/home/nicky/STIXCore/stixcore/products/level0/scienceL0.py", line 279, in from_levelb
    packets, idb_versions, control = ScienceProduct.from_levelb(levelb, parent=parent)
  File "/home/nicky/STIXCore/stixcore/products/level0/scienceL0.py", line 163, in from_levelb
    packets, idb_versions = GenericProduct.getLeveL0Packets(levelb)
  File "/home/nicky/STIXCore/stixcore/products/product.py", line 584, in getLeveL0Packets
    packets = [Packet(d) for d in levelb.data['data']]
  File "/home/nicky/STIXCore/stixcore/products/product.py", line 584, in <listcomp>
    packets = [Packet(d) for d in levelb.data['data']]
  File "/home/nicky/STIXCore/stixcore/tmtc/packet_factory.py", line 91, in __call__
    return self.tm_packet_factory(packet)
  File "/home/nicky/STIXCore/stixcore/tmtc/packet_factory.py", line 102, in __call__
    return self._check_registered(data)
  File "/home/nicky/STIXCore/stixcore/tmtc/packet_factory.py", line 66, in _check_registered
    return PacketType(*args, **kwargs)
  File "/home/nicky/STIXCore/stixcore/tmtc/packets.py", line 541, in __init__
    data, structure = parse_variable(self.source_packet_header.bitstream, tree)
  File "/home/nicky/STIXCore/stixcore/tmtc/parser.py", line 232, in parse_variable
    _parse_tree(bitstream, tree, fields)
  File "/home/nicky/STIXCore/stixcore/tmtc/parser.py", line 203, in _parse_tree
    _parse_tree(bitstream, pnode, children)
  File "/home/nicky/STIXCore/stixcore/tmtc/parser.py", line 203, in _parse_tree
    _parse_tree(bitstream, pnode, children)
  File "/home/nicky/STIXCore/stixcore/tmtc/parser.py", line 203, in _parse_tree
    _parse_tree(bitstream, pnode, children)
  File "/home/nicky/STIXCore/stixcore/tmtc/parser.py", line 195, in _parse_tree
    raise e
  File "/home/nicky/STIXCore/stixcore/tmtc/parser.py", line 193, in _parse_tree
    raw_val, children = (bitstream.read(pnode.parameter.bin_format), [])
  File "/home/nicky/STIXCore/venv/lib/python3.8/site-packages/bitstring.py", line 3959, in read
    value, self._pos = self._readtoken(name, self._pos, length)
  File "/home/nicky/STIXCore/venv/lib/python3.8/site-packages/bitstring.py", line 2096, in _readtoken
    raise ReadError("Reading off the end of the data. "
bitstring.ReadError: Reading off the end of the data. Tried to read 8 bits when only 0 available.
2022-07-10 02:39:00,827 Reading off the end of the data. Tried to read 8 bits when only 0 available.

**Comment by nicHoch** [comment]
so this is quite a mystery:

it looks like that one package in a sequence of around 400 can not be parsed with the version 2.26.36/35 but with older versions as '2.26.31..34

i have no idea how this package would have been generated with an old application version but the next one in the row (and also the previous one) with the correct version.
```

index sequence_count scet_coarse time_sync
----- -------------- ----------- ---------
  225           4388   702730735      True
  226           4389   702730735      True
  227           4390   702730736      True
  228           4391   702730736      True
  229           4392   702730737      True
  230           4393   702730737      True
  231           4394   702730738      True
  232           4395   702730738      True
  233           4396   702730739      True
  234           4397   702730739      True
  235           4398   702730740      True
```
the off package is number `231`

 ```
idbm = IDBManager(Path("/home/nicky/STIXCore/stixcore/data/idb"))
    data = '0x'+'0dbc112a0f781015060029e2d1f283b015005bf36683516d01242b29c36b5900000001000794000c000100020004000800100020004000800100020004000800ffffffff00082b2b282529282a2b2c292a2a2329292a0a0101018000000000020100000000000000000000000100020000000000000002000000000000000000322e31352e3035365f3635305f325f31303032202d3e20496e6a65637465643a20393925206f66207468652066696c652e000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000100000000000000000001000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000100000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000001000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000e0e018000000000000000000000000000000000000000000000000000000000000000010000000000000000010000000000000000000000000000000000000000000000003002000000000000b40000000000000086000000000000008600000000000000ffffffff000000005b544d46495d20496e6a656374696e67207468652066696c653a202f686f6d652f736f6c6f6f70732f646174612f444c502f7265636f6e737472756374656446696c65732f31375f323032322e3130352e31312e35322e31352e3035365f3635305f325f31303032202d3e20496e6a65637465643a20393925206f66207468652066696c652e00000000000000000000a10f000000000000780000f46b7f0000780000f46b7f000000000000000000000000000000000000352e31322e31362e33333e5b544d46495d20496e6a656374696e67207468652066696c653a202f686f6d652f736f6c6f6f70732f646174612f444c502f7265636f6e737472756374656446696c65732f31375f323032322e3130352e31312e35322e31352e3035365f3635305f325f31303032202d3e20496e6a65637465643a20393925206f66207468652066696c652e00000000000000e10e000000000000780000f46b7f0000d05b00f46b7f00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000100000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000001000000000000000000000000000000000000000000000010100180000000000000000000000000000000000000000000000000000001000000000000000000000000000000000000010000000000000100000000000000000000010001000000000000000000010000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000010000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000010000000000000000000001000000000000000000000000000000000000000000000000000000000000000000111101800000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000100000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000010000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000100000000000000000000000000000000000001000000000000000000000000000000000000000000000000000000010000000000000000000000000000000000000000000100000000000000000000000000000100000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000001212018001000002010000000000000000000101010000010000000001000201010101030000000001000001000100000000000000000000000000000000000000000101000100000000010000000000010002000000000000000100000000010000000000000000000002000000000000000101000001000000000002000000000000000000000000000000000000000000000000000200000101000000000001000000020000000000000000000001010101000000000000020002000100000000000000010001000100000000020000030000010103010000000001000000000000000000000001000001000001000000000001000100000001000000000001000002000100010000000000010100000100000000000000000200000001000000000001000000000000000000000000000102000100010000000000000001000200000000000001000001010101000000000001010100000100000000000001000200000000000000000000000203010002000000000000000000000000010000000013130180000001000000000000000000000000000100000000000000000000000000000000000000000000000000000000000000000000000000000000000000000100000000000000000000000100000000000000000000000000000000000000000000000000000000000000000000000000000001010000000000000000000001000100000000000000000000000000000000000000000000000000000000000001000000000000000000000000000000000000000000000000000000000000000000000000000001000100000000000000000000000000000000010000000000000000000000000000000000000000000000000000000000000000000000000100000000000000000000000000000000000000000000000100000000000000000000000000000000000000000000000100010000000000000000000000000100000000000000000000000000010100000000000000000000000000000000010000000000000000000000000100010000000000000000000000000001000000000000141401800000000000000000000000010000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000010000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000001000000000000000000000000000000000000000000000000000000000000000000000000000100000000000000000000000100000000000000000000000000000000000000001515018000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000100000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000001000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000016160180000000000000000000000000000000000000010000000000000000000000000000000000000000000000000100000000000000000000000000000000000000000000000000000000000000000000000100000000000000000000000100000000000000000000000000000000000000000000000100000000000000000100000000000000000000000000000000000000010000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000010000000000000000010000000000000000000000000000000000000000000001000000000000000000000000000000000000010000000000000000000000000000000000000000000000' # noqa:    
    good_version = []

    for v in idbm.get_versions():
        print(f"try version {v['label']}")
        try:
            idb = idbm.get_idb(v['label'])
            packet = GenericTMPacket(data, idb=idb)
            packet.print(descr=True)
            good_version.append(v)
        except Exception:
            pass
    
    logger.warning(good_version)
    assert len(good_version) > 0

    assert False
```

the packet meta data and the error is the following

```
ERROR    stixcore.tmtc.packets:packets.py:545 Packet parsing error: GenericTMPacket(SourcePacketHeader(version=0, packet_type=0, header_flag=1, process_id=91, packet_category=12, sequence_flag=0, sequence_count=4394, data_length=3960), TMDataHeader(pus_version=1, service_type=21, service_subtype=6, destination_id=0, scet_coarse=702730738, scet_fine=33712, datetime=702730738:33712))
idb version:IDB(2.26.35, /home/nicky/STIXCore/stixcore/data/idb/v2.26.35/idb.sqlite)
packet data:0x0dbc112a0f781015060029e2d1f283b015005bf36683516d01242b29c36b5900000001000794000c000100020004000800100020004000800100020004000800ffffffff00082b2b282529282a2b2c292a2a2329292a0a0101018000000000020100000000000000000000000100020000000000000002000000000000...
```

**Comment by nicHoch** [comment]
@drhlxiao do you know if there was something of with the instrument on `2022-04-08T11:00:52.220`

**Comment by nicHoch** [comment]
maybe due to packet corruption?
this will not be fixed - we have to take care manually in the very seldom cases.
