### ISSUE TITLE
 TM Processing L0: 3,25,2 hk-maxi 

### ISSUE THREAD

**Issue by nicHoch** [i4Ds/STIXCore#252]
2022-07-10 16:31:22,515 MergeConflictWarning: Cannot merge meta key 'CHECKSUM' types <class 'str'> and <class 'str'>, choosing CHECKSUM='ToDBWm99TmAATm97'
2022-07-10 16:31:22,516 MergeConflictWarning: Cannot merge meta key 'DATASUM' types <class 'str'> and <class 'str'>, choosing DATASUM='1058969377'
2022-07-10 16:31:22,524 Error processing file /data/stix/out/test/bsdfull/L0/3/25/2/solo_L0_stix-hk-maxi_0692323200_V01.fits
Traceback (most recent call last):
  File "/home/nicky/STIXCore/stixcore/processing/L0toL1.py", line 69, in process_type
    files = processor.write_fits(l1)
  File "/home/nicky/STIXCore/stixcore/io/fits/processors.py", line 762, in write_fits
    prod = prod + existing
  File "/home/nicky/STIXCore/stixcore/products/product.py", line 495, in __add__
    data = vstack((self.data, other_data))
  File "/home/nicky/STIXCore/venv/lib/python3.8/site-packages/astropy/table/operations.py", line 651, in vstack
    out = _vstack(tables, join_type, col_name_map, metadata_conflicts)
  File "/home/nicky/STIXCore/venv/lib/python3.8/site-packages/astropy/table/operations.py", line 1393, in _vstack
    col_cls = _get_out_class(cols)
  File "/home/nicky/STIXCore/venv/lib/python3.8/site-packages/astropy/table/operations.py", line 88, in _get_out_class
    raise ValueError('unmergeable object classes {}'
ValueError: unmergeable object classes ['Column', 'Quantity']
2022-07-10 16:31:22,526 unmergeable object classes ['Column', 'Quantity']
2022-07-10 16:31:23,169 VerifyWarning: Card is too long, comment will be truncated.
2022-07-10 16:31:23,315 VerifyWarning: Card is too long, comment will be truncated.
2022-07-10 16:31:23,317 VerifyWarning: Card is too long, comment will be truncated.
2022-07-10 16:31:23,521 VerifyWarning: Card is too long, comment will be truncated.

**Comment by nicHoch** [comment]
i had to inject the x4 % unit for the cpu_load into older IDB version for uniform data type over entire mission

**Comment by nicHoch** [comment]
note: `%` will become  `Unit(dimensionless with a scale of 0.01)` after FITS in/out
