### ISSUE TITLE
 TM Processing L0: raw to engeneering fails

### ISSUE THREAD

**Issue by nicHoch** [i4Ds/STIXCore#254]
2022-07-10 16:19:21,906 VerifyWarning: Card is too long, comment will be truncated.
2022-07-10 16:19:22,000 Error processing file /data/stix/out/test/bsdfull/L0/21/6/41/solo_L0_stix-cal-energy_0692323200_V01.fits
Traceback (most recent call last):
  File "/home/nicky/STIXCore/stixcore/processing/L0toL1.py", line 68, in process_type
    l1 = tmp.from_level0(l0, parent=file.name)
  File "/home/nicky/STIXCore/stixcore/products/product.py", line 658, in from_level0
    engineering.raw_to_engineering_product(l1, idbm)
  File "/home/nicky/STIXCore/stixcore/processing/engineering.py", line 156, in raw_to_engineering_product
    calib_param = idb.get_params_for_calibration(
IndexError: list index out of range
2022-07-10 16:19:22,001 list index out of range
2022-07-10 16:19:22,015 VerifyWarning: Card is too long, comment will be truncated.
2022-07-10 16:19:22,102 VerifyWarning: Card is too long, comment will be truncated.

**Comment by nicHoch** [comment]
there is a idb version change in the middle of the product. v35 has injected calibration params v36 has manual added.
it is not possible to store two different IDB conversions (IDs) for the same data column. 

so will not be fixed we have to manually take care in the very rare situations.

**Comment by nicHoch** [comment]
we can look the right ID on the fly so reopen
