### ISSUE TITLE
More spice errors in logs

### ISSUE THREAD

**Issue by samaloney** [i4Ds/STIXCore#362]
Need to check if fix in #356 was applied or this needs an update

http://pub099.cs.technik.fhnw.ch/fits/logging/STIX_TM_16_BatchRequest.PktTmRaw.SOL.0.2023.214.07.24.03.257.VLTY@2023.243.16.00.01.589.1.xml.log.err
http://pub099.cs.technik.fhnw.ch/fits/logging/STIX_TM_16_BatchRequest.PktTmRaw.SOL.0.2023.214.07.24.03.259.OzQE@2023.245.16.00.01.890.1.xml.log.err

Looking at the error and checking the code it seems the fix was not running when the TM was processed
```
"""
Traceback (most recent call last):
  File "/usr/lib/python3.9/concurrent/futures/process.py", line 246, in _process_worker
    r = call_item.fn(*call_item.args, **call_item.kwargs)
  File "/home/stixcore/STIXCore/stixcore/processing/L1toL2.py", line 106, in process_type
    all_files.extend(idlprocessor.process())
  File "/home/stixcore/STIXCore/stixcore/processing/sswidl.py", line 205, in process
    files.extend(task.run(self.fits_processor))
  File "/home/stixcore/STIXCore/stixcore/processing/sswidl.py", line 153, in run
    self._results = self.postprocessing(results, fits_processor)
  File "/home/stixcore/STIXCore/stixcore/products/level2/housekeepingL2.py", line 289, in postprocessing
    orient, dist, car, heeq = Spice.instance.get_auxiliary_positional_data(date=d)
  File "/home/stixcore/STIXCore/stixcore/ephemeris/manager.py", line 303, in get_auxiliary_positional_data
    cmat, _ = spiceypy.ckgp(SOLAR_ORBITER_STIX_ILS_FRAME_ID, sc, 1.0, 'SOLO_SUN_RTN')
  File "/home/stixcore/STIXCore/venv/lib/python3.9/site-packages/spiceypy/spiceypy.py", line 138, in with_errcheck
    res = f(*args, **kwargs)
  File "/home/stixcore/STIXCore/venv/lib/python3.9/site-packages/spiceypy/spiceypy.py", line 158, in wrapper
    raise NotFoundError(
spiceypy.utils.exceptions.NotFoundError: Spice returns not found for function: ckgp
"""
```
as line 303 is no longer in the `get_auxiliary_positional_data` on latest tag

https://github.com/i4Ds/STIXCore/blob/f628d3e7892542a33745d23b571962bd4d94f9fb/stixcore/ephemeris/manager.py#L296-L314

I was able to confirm the version of the running pipelines is v1.0.0 and not 1.1.0 which has the fix.

```shane@pub099:/data/stix/out/fits_v1.0.0/logging$ source /home/stixcore/STIXCore/venv/bin/activate
(venv) shane@pub099:/data/stix/out/fits_v1.0.0/logging$ python
Python 3.9.16 (main, Feb 14 2023, 14:04:16)
[GCC 9.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import stixcore
>>> stixcore.__version__
'1.0.0'

Reprocessing this TM with the updated should resolve the issue.

**Comment by nicHoch** [comment]
closed with #356
